name: Colin Chang
description: Colin Chang's blog and project repository
url: http://colinichang.com
safe: true #Github Pages overrides lsi to safe
lsi: false #Github pages overrides lsi to false

sass:
    sass_dir: styles
    style: :compressed

paginate: 5
paginate_path: "/page:num"